### PR TITLE
Added local date option for the package

### PR DESCRIPTION
**Pull request by tHBp**
@sindresorhus Changes made as per suggestions. Please review. Thanks.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I appreciate the pull request, but it's just too far from what I'd like to see. I've implemented the change myself and done a new release. You can now bump the dependendency in your `time-grunt` PR ;)

**Comment by tHBp** [comment]
Nice implementation, using `time-zone`. However, I can't help but notice, it uses `getTimezoneOffset`. As far as I know, this method needs some adjustment to make it work correctly for countries which use DST.
Personally, it doesn't affect me because we don't use daylight time savings here.

**Comment by sindresorhus** [comment]
@tHBp Seems to work fine with DST. I tried it with different dates and it correctly changed the timezone between `+2` and `+1` (I'm in Norway).

**Comment by SamVerschueren** [comment]
Using it as well in [tz-format](https://github.com/SamVerschueren/tz-format/blob/master/index.js#L14) and never experienced issues with that method.

**Comment by tHBp** [comment]
@SamVerschueren Well it is all good then :)

**Pull request closed without merging**
